[project]
name = "azure-ai-engineer-associate-practicals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "azure-ai-documentintelligence>=1.0.2",
    "azure-ai-ml>=1.28.1",
    "azure-ai-projects>=1.0.0",
    "azure-ai-textanalytics>=5.3.0",
    "azure-ai-translation-document==1.0.0",
    "azure-ai-translation-text==1.0.0b1",
    "azure-cognitiveservices-speech>=1.45.0",
    "azure-identity>=1.24.0",
    "azureml-mlflow>=1.60.0",
    "langchain-openai>=0.3.30",
    "mlflow>=3.3.1",
    "openai>=1.99.9",
    "python-dotenv>=1.1.1",
]
